print("             /¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯\                                              ")
print("            /                                  \                                             ")
print("           /                                    \                                            ")
print("          /                                      \                                           ")
print("         /                                        \                                           ")
print("        /                                          \                                         ")
print("       /                                            \                                       ")
print("      |      Bienvenido a mi pequeña versión de:     |                                      ")
print("      |                   Pokemón                    |                                      ")
print("      |                                              |                                       ")
print("      |¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯/¯¯¯¯¯\¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|                                       ")
print("      |                  /       \                   |                                       ")
print("      |                  \       /                   |                                       ")
print("      |___________________\_____/____________________|                                       ")
print("      |                                              |                                       ")
print("      |                                              |                                       ")
print("       \                                            /                                        ")
print("        \                By:Ἄτλας                  /                                         ")
print("         \                                        /                                          ")
print("          \                                      /                                          ")
print("           \                                    /                                            ")
print("            \                                  /                                             ")
print("             \________________________________/                                             ")


